<a href="https://colab.research.google.com/github/Kuntol772/Python-Beginner/blob/main/AI_lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(type(a))
print(a.ndim)
print("row 0 and collumn 1 =",a[0,1])
print(a[1,0:2])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
row 0 and collumn 1 = 2
[4 5]


In [ ]:
a=np.array([1,2,3,4])
a2=np.array([[1,2,3,4],[5,6,7,8]])
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a2[1,3])
print(a3[0,2,2])

8
9


In [ ]:
arr = np.array([1, 2, 3, 4])
arr1 = np.array([1.2,3,4,5])
arr2 = np.array(["Rohim","Karim","Modu","Kodu"])
print(arr.dtype)
print(arr1.dtype)
print(arr2.dtype)

int64
float64
<U5


In [ ]:
arr=np.array([1.2,4.3,3.1])
arr1=arr.astype('i')
arr1=arr.astype(int)
print(arr)
print(arr1)
print(arr1.dtype)

[1.2 4.3 3.1]
[1 4 3]
int64


In [ ]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=13
print(arr)
print(x)

[13  2  3  4  5]
[1 2 3 4 5]


In [ ]:
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a3.shape)

(1, 3, 3)


In [ ]:
a=np.array([1,2,3],ndmin=4)
print(a)
print(a.shape)

[[[[1 2 3]]]]
(1, 1, 1, 3)


In [ ]:
a=np.array([1,2,3,4,5,6])
a1=a.reshape(2,3)
print(a1)

[[1 2 3]
 [4 5 6]]


In [ ]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
for i in a2:
  print(i)

[1 2 3 4]
[5 6 7 8]


In [ ]:
a2=np.array([[1,2,3,4],[5,6,7,8]])
for i in a2:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
a3=np.concatenate((a1,a2))
print(a3)

[1 2 3 4 5 6 7 8]


In [ ]:
a2=np.array([[1,2,3],[5,6,7]])
a3=np.array([[12,13,45],[11,14,15]])
a=np.concatenate((a2,a3),axis=0)
print(a)
a=np.concatenate((a2,a3),axis=1)
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [12 13 45]
 [11 14 15]]
[[ 1  2  3 12 13 45]
 [ 5  6  7 11 14 15]]


In [ ]:
a=np.array([1,2,3,4,5,6])
new=np.where(a==4)
print(new)

(array([3]),)
